In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'x1':[3,2,3,1,4,5],
                   'x2':[1,5,1,3,1,2],
                   'x3':[4,1,4,2,1,4],
                   'y':[4.1,4.3,2.1,3.3,4.1,3.5]})
df

x1  x2  x3    y
0   3   1   4  4.1
1   2   5   1  4.3
2   3   1   4  2.1
3   1   3   2  3.3
4   4   1   1  4.1
5   5   2   4  3.5

In [ ]:
#Nodo1:

nodo_a = [df.iloc[0], df.iloc[2]]
nodo_b = [df.iloc[1],df.iloc[3]]
nodo_c = [df.iloc[4]]
nodo_d = [df.iloc[5]]


In [ ]:
nodo_a

[x1    3.0
 x2    1.0
 x3    4.0
 y     4.1
 Name: 0, dtype: float64,
 x1    3.0
 x2    1.0
 x3    4.0
 y     2.1
 Name: 2, dtype: float64]

In [ ]:
(4.1+2.1)/2

3.0999999999999996

In [ ]:
nodo_b

[x1    2.0
 x2    5.0
 x3    1.0
 y     4.3
 Name: 1, dtype: float64,
 x1    1.0
 x2    3.0
 x3    2.0
 y     3.3
 Name: 3, dtype: float64]

In [ ]:
(4.3+3.3)/2

3.8

In [ ]:
nodo_c

[x1    4.0
 x2    1.0
 x3    1.0
 y     4.1
 Name: 4, dtype: float64]

In [ ]:
nodo_d

[x1    5.0
 x2    2.0
 x3    4.0
 y     3.5
 Name: 5, dtype: float64]

In [ ]:
#Usando KNN para predecir:

#Cantidad de vecinos =3

from sklearn.metrics import pairwise_distances

x = df.drop(columns='y').copy()
y = df['y'].copy()

pairwise_distances(x,[[0,1,3]])

array([[3.16227766],
       [4.89897949],
       [3.16227766],
       [2.44948974],
       [4.47213595],
       [5.19615242]])

In [ ]:
#Calculo y promedio las 3 distancias más cercanas
 (3.16+3.16+2.44)/3

2.92

In [ ]:
#Etiquetas de nodos
y[0],y[2],y[3]

(4.1, 2.1, 3.3)

In [ ]:
#Promedio de los nodos
(4.1+2.1+3.3)/3

3.1666666666666665

El resultado es cercano

**SKLEARN**

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
arbol = DecisionTreeRegressor()
vecinos = KNeighborsRegressor()

In [ ]:
arbol.fit(x,y)
vecinos.fit(x,y)

KNeighborsRegressor()

In [ ]:
arbol.predict([[0,1,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([3.1])

In [ ]:
vecinos.predict([[0,1,3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([3.58])